import React from 'react'
import Navbar from './Navbar'

import Head from 'next/head'
import Addnote from './Addnote'
import Notes from './Notes'

export default function Layout({ childrens }) {
    return (
        <div>
            <Head>
                <title>Notebook</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossOrigin="anonymous"></script>
            </Head>

            <Navbar />
            <Addnote/>
            <Notes/>
            {childrens}
        </div>
    )
}
